# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b26451c0624dc8d83079b8aa23801adb51690a9ca8862f8379bbf72ee16a3dfa2092d01150347e1e903cc2c0804755e9e2ad5d3aa834c210195bdf198701419

test:
  secret_key_base: 53389342557a54c83db05bb433b521581294f0b2ca16fd1c91585ef0af68a7ca055ba49d6def844a701375b7ca194148790ffde3dd0f74bfeb7bfe7a1f6a70f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
